### ISSUE TITLE
how to の2ページ目をセンター寄せにする

### ISSUE THREAD

**Issue by kanakanasan** [kanakanasan/myapp#25]

**Comment by hizatama** [comment]
長さが可変のときは以下のように
子をdisplay:inline-block
親をtext-align:center
にすればいけるはず。
孫要素（.body）の幅を指定してあげるのもミソ。
＃早くscssコンパイル環境整えないと…

Kanatis.scss

``` css
    .page2 {
        margin-top: 70px;
        text-align: center;
        > div {
            display: inline-block;
            color: rgb(97, 97, 97);
        }
        .body {
            width: 220px;
        }
    }
```
